### ISSUE TITLE
[bug] Date Jumping ahead

### ISSUE THREAD

**Issue by getglimpses** [getglimpses/community#4]
**Describe the bug**
Last reported by F. Fehse
In some occasions, the date on the notes is a day ahead and I see no option to make sure the program is in the right time-zone…

**To Reproduce**
Create an entry around 11.42 PM

**Expected behaviour**
the app should show the current date

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/41840090/66644924-19f06300-ec1a-11e9-9ae9-5c5e8ac784c0.jpg)

**Comment by aneesahammed** [comment]
Fix is released with the latest version -0.15.0.25338
