### ISSUE TITLE
[feature] Export all entries to .TXT & JSON

### ISSUE THREAD

**Issue by getglimpses** [getglimpses/community#6]
As a user, I should be able to export all my entries to text format and JSON format so that I will not be tied with one journal app 'glimpses'.

**Describe the solution you'd like**
Option to select .text and .JSON formats while exporting all the entries.

**Describe alternatives you've considered**
Single each entry with only pdf export is tedious

**Comment by aneesahammed** [comment]
Feature is implemented & released with the latest version -0.15.0.25338
<img width="597" alt="export-json-text" src="https://user-images.githubusercontent.com/41840090/66701193-85f1ca80-ecf1-11e9-80ec-f3b881319069.png">
